name: CI

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - .vscode

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2

      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - run: pnpm install
      - run: pnpm test

  # notify:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - test
  #   steps:
  #     - name: DingDing notify only Push
  #       uses: zcong1993/actions-ding@master
  #       if: github.event_name == 'push'
  #       with:
  #         dingToken: ${{ secrets.DING_TOKEN }}
  #         body: |
  #           {
  #             "msgtype": "markdown",
  #             "markdown": {
  #               "title": "${{ github.repository }} 仓库推送成功",
  #               "text": "![Random Picture](https://picsum.photos/400/200) \n GitHub 仓库 ${{ github.repository }} 推送成功。\n - [查看文档](https://qxy-fe.github.io/fe-docs/utils-lib/eslint.html) \n - [查看仓库](https://github.com/${{ github.repository }})"
  #             }
  #           }
